# Generated by Django 4.2.11 on 2024-06-03 16:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_rename_date_bookingsystem_date_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='bookingsystem',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, default=datetime.datetime(2024, 6, 3, 16, 32, 6, 959762, tzinfo=datetime.timezone.utc), primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='bookingsystem',
            name='number_of_people',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')]),
        ),
        migrations.AlterField(
            model_name='bookingsystem',
            name='time',
            field=models.TimeField(choices=[(datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00')]),
        ),
        migrations.AlterField(
            model_name='bookingsystem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
