# Generated by Django 4.2.11 on 2024-09-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_bookingsystem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsystem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
